#!/usr/bin/env python
"""Regenerate ``docs/permissions.md`` from the tool descriptions themselves.

Every tool names the delegated permission it needs in its own description —
that text is what the model reads, so it is already kept accurate. Deriving the
matrix from it means the document cannot drift from the code: add a tool and
the table gains a row, change a permission and the table follows.

``tests/test_permissions_doc.py`` fails if the committed file does not match
what this produces, so the drift is caught in CI rather than by a reader.

    uv run python scripts/generate_permissions.py          # write the file
    uv run python scripts/generate_permissions.py --check  # exit 1 if stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import ms_graph_mcp  # noqa: F401  (import registers every @tool)
from ms_graph_mcp.allowlists import (
    INTERNAL_TOOL_NAMES,
    READ_TOOL_NAMES,
    WRITE_TOOL_NAMES,
)
from ms_graph_mcp.tooling import get_registry

DOC = Path(__file__).resolve().parent.parent / "docs" / "permissions.md"

# "Requires Mail.Read." / "Requires A and B." / "Requires A, B and C."
_REQUIRES = re.compile(r"Requires ([A-Za-z][A-Za-z.]*(?:(?:,\s*|\s+and\s+)[A-Za-z][A-Za-z.]*)*)\.")


def permissions_for(description: str) -> list[str]:
    found: list[str] = []
    for match in _REQUIRES.findall(description):
        for part in re.split(r",\s*|\s+and\s+", match):
            cleaned = part.strip().rstrip(".")
            if cleaned and cleaned not in found:
                found.append(cleaned)
    return found


def _first_sentence(description: str) -> str:
    sentence = description.split(". ")[0].strip()
    return sentence if sentence.endswith(".") else sentence + "."


def _namespace(name: str) -> str:
    return name.split("_", 1)[0]


def _rows(names: tuple[str, ...]) -> list[tuple[str, str, str]]:
    registry = get_registry()
    rows = []
    for name in sorted(names):
        spec = registry.get(name)
        perms = permissions_for(spec.description)
        rows.append(
            (name, ", ".join(f"`{p}`" for p in perms) or "—", _first_sentence(spec.description))
        )
    return rows


def _table(names: tuple[str, ...]) -> str:
    out = ["| Tool | Delegated permission | What it does |", "|---|---|---|"]
    current = None
    for name, perms, summary in _rows(names):
        ns = _namespace(name)
        if ns != current:
            current = ns
            out.append(f"| **{ns}** | | |")
        out.append(f"| `{name}` | {perms} | {summary} |")
    return "\n".join(out)


def _scope_set(names: tuple[str, ...]) -> list[str]:
    registry = get_registry()
    found: set[str] = set()
    for name in names:
        found.update(permissions_for(registry.get(name).description))
    return sorted(found)


def render() -> str:
    read_scopes = _scope_set(READ_TOOL_NAMES)
    write_only = sorted(set(_scope_set(WRITE_TOOL_NAMES)) - set(read_scopes))

    return f"""<!-- Generated by scripts/generate_permissions.py. Do not edit by hand. -->
# Delegated permissions

Every tool and the Microsoft Graph delegated permission it needs. Generated from the tool
descriptions, so it cannot drift from the code.

This server only ever uses **delegated** permissions — it acts as the signed-in user and can never
see more than they can. There are no application permissions anywhere in the tool surface.

See the [README](https://github.com/nitin27may/ms-graph-mcp/blob/main/README.md#set-up-the-entra-app) for the app-registration walkthrough, and
[configuration.md](configuration.md) for the settings. This document is the reference for *which*
permissions to grant.

## Consent sets

Paste one of these into `GRAPH_MCP_SCOPES`, and add the matching permissions under **API
permissions → Microsoft Graph → Delegated** in the portal. The two must agree: if a scope is
requested but not consented, sign-in still succeeds and the tool later returns `SCOPE_DENIED`
naming the one that is missing.

### Read-only — {len(READ_TOOL_NAMES)} tools, nothing can be changed or sent

```
{",".join(read_scopes)}
```

### Adding write access — {len(WRITE_TOOL_NAMES)} further tools

Append these to the read set. They let an agent send mail, book meetings, post to Teams and change
files **as the user**, so grant them deliberately.

```
{",".join(write_only)}
```

Write tools also need `GRAPH_MCP_WRITE_SCOPE=true`; the scopes alone are not enough. After changing
scopes, delete `~/.ms-graph-mcp/token_cache.json` to force a fresh consent — the cached token
carries only what was originally granted.

## Read tools

{_table(READ_TOOL_NAMES)}

## Write tools

Reachable only when the caller supplies write scope, and never when `GRAPH_MCP_READ_ONLY` is set.

{_table(WRITE_TOOL_NAMES)}

## Internal tools

Not part of the agent surface. Reachable only by the shared-secret machine principal together with
`X-Internal-Scope: true`, and never advertised to an LLM client. They exist for first-party ETL and
service callers.

{_table(INTERNAL_TOOL_NAMES)}

## Notes

- **`SCOPE_DENIED` names the permission it needed.** The error is terminal and not retryable — a
  model receiving it should tell the user what to request rather than trying again.
- **Guest accounts cannot enumerate the directory.** `directory_search_users` and
  `directory_search_groups` fail for guests regardless of consent; Microsoft blocks the query
  itself, not the permission.
- **The OneNote API has no application-permission support at all**, so those tools are delegated by
  necessity rather than by choice.
- **`X-Entra-App-Token`** is an optional separate app-only token, used only for tenant-wide group
  lookups that delegated permissions cannot cover. It is never required.
"""


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        if not DOC.exists():
            print(f"{DOC} does not exist — run scripts/generate_permissions.py")
            return 1
        if DOC.read_text(encoding="utf-8") != rendered:
            print(f"{DOC} is out of date — run scripts/generate_permissions.py")
            return 1
        print(f"{DOC} is up to date")
        return 0
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(rendered, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
